"use client";

import { useEffect, useState } from "react";
import { Button, Input, Panel, Toast } from "../../../components/ui";
import { WorkspaceGuard } from "../../../components/workspace-guard";
import { getCurrentUser, getSlides, getTopics, saveSlides, saveTopics } from "../../../lib/storage";
import type { Slide, Topic } from "../../../lib/types";
import { makeId } from "../../../lib/utils";

export default function AdminPage() {
  const [topics, setTopics] = useState<Topic[]>([]); const [slides, setSlides] = useState<Slide[]>([]); const [topicName, setTopicName] = useState(""); const [topic, setTopic] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { setTopics(getTopics()); setSlides(getSlides()); }, []);
  const createTopic = () => { const name = topicName.trim(); if (!name) return; if (topics.some((item) => item.name.toLowerCase() === name.toLowerCase())) return setNotice("That topic already exists."); const next = [...topics, { name, creator: getCurrentUser() || "learner", createdAt: new Date().toISOString() }]; setTopics(next); saveTopics(next); setTopicName(""); setNotice("Topic created."); };
  const addSlide = () => { if (!topic || !title.trim()) return setNotice("Choose a topic and add a slide title."); const next = [...slides, { id: makeId(), topic, title: title.trim(), description: description.trim(), creator: getCurrentUser() || "learner" }]; setSlides(next); saveSlides(next); setTitle(""); setDescription(""); setNotice("Slide added."); };
  const deleteTopic = (name: string) => { const nextTopics = topics.filter((item) => item.name !== name); const nextSlides = slides.filter((item) => item.topic !== name); setTopics(nextTopics); setSlides(nextSlides); saveTopics(nextTopics); saveSlides(nextSlides); };
  return <WorkspaceGuard><div className="mx-auto max-w-7xl px-6 py-10">{notice && <Toast message={notice} type="success" />}<header className="mb-8"><p className="text-xs font-bold uppercase tracking-[.15em] text-brick">Workspace setup</p><h1 className="mt-2 text-4xl font-black text-maroon">Content Manager</h1><p className="mt-2 text-muted">Create topics, compose slides, and organize your knowledge base.</p></header><div className="grid gap-6 lg:grid-cols-[360px_1fr]"><aside className="space-y-6"><Panel><h2 className="text-lg font-bold text-maroon">▣ Create a new topic</h2><Input className="mt-5" value={topicName} onChange={(e) => setTopicName(e.target.value)} placeholder="e.g. Pharmacology Basics" /><Button className="mt-3 w-full" onClick={createTopic}>+ Create topic</Button></Panel><Panel><h2 className="text-lg font-bold text-maroon">▦ Add a slide</h2><select value={topic} onChange={(e) => setTopic(e.target.value)} className="mt-5 w-full rounded-xl border border-line bg-[#fcf7f6] px-4 py-3 text-sm outline-none"><option value="">Choose a topic</option>{topics.map((item) => <option key={item.name}>{item.name}</option>)}</select><Input className="mt-3" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Slide title" /><textarea value={description} onChange={(e) => setDescription(e.target.value)} className="mt-3 min-h-28 w-full rounded-xl border border-line bg-[#fcf7f6] px-4 py-3 text-sm outline-none focus:ring-4 focus:ring-tint" placeholder="Slide description (optional)" /><Button className="mt-3 w-full" onClick={addSlide}>Add slide</Button></Panel></aside><Panel><h2 className="mb-5 text-lg font-bold text-maroon">▤ Existing topics & slides</h2>{topics.length === 0 ? <p className="text-sm text-muted">No topics yet.</p> : <div className="space-y-5">{topics.map((item) => <div key={item.name} className="rounded-xl border border-line p-4"><div className="flex items-center justify-between gap-4"><h3 className="font-bold text-maroon">{item.name}</h3><button onClick={() => deleteTopic(item.name)} className="text-xs font-bold text-red-600">Delete</button></div>{slides.filter((slide) => slide.topic === item.name).map((slide) => <div key={slide.id} className="mt-3 rounded-lg bg-soft p-3"><p className="font-semibold text-ink">{slide.title}</p><p className="mt-1 text-xs text-muted">{slide.description || "No description"}</p></div>)}</div>)}</div>}</Panel></div></div></WorkspaceGuard>;
}
