"use client";

import { useEffect, useState } from "react";
import { Button, Toast } from "../../../components/ui";
import { WorkspaceGuard } from "../../../components/workspace-guard";
import { getBoardEntries, saveBoardEntries } from "../../../lib/storage";
import type { BoardEntry } from "../../../lib/types";
import { makeId } from "../../../lib/utils";

export default function BoardPage() {
  const [content, setContent] = useState(""); const [entries, setEntries] = useState<BoardEntry[]>([]); const [light, setLight] = useState(false); const [fontSize, setFontSize] = useState(32); const [notice, setNotice] = useState("");
  useEffect(() => { setEntries(getBoardEntries()); setLight(window.localStorage.getItem("sunesisWordLightMode") === "true"); setFontSize(Number(window.localStorage.getItem("sunesisWordFontSize")) || 32); }, []);
  const save = () => { if (!content.trim()) return; const next = [...entries, { id: makeId(), content: content.trim(), createdAt: new Date().toISOString() }]; setEntries(next); saveBoardEntries(next); setNotice("Write-up saved successfully."); };
  const removeLast = () => { if (!entries.length) return setNotice("No saved write-ups found."); const next = entries.slice(0, -1); setEntries(next); saveBoardEntries(next); setContent(""); };
  const clear = () => { setEntries([]); saveBoardEntries([]); setContent(""); };
  return <WorkspaceGuard><div className="mx-auto max-w-5xl px-6 py-10">{notice && <Toast message={notice} />}<header className="mb-8"><p className="text-xs font-bold uppercase tracking-[.15em] text-brick">Thinking space</p><h1 className="mt-2 text-4xl font-black text-maroon">Typing board</h1><p className="mt-2 text-muted">Write, save, and revisit your explanations.</p></header><div className="mb-4 flex flex-wrap gap-2"><button onClick={() => { const next = !light; setLight(next); window.localStorage.setItem("sunesisWordLightMode", String(next)); }} className="rounded-lg border border-line bg-white px-3 py-2 text-sm font-bold text-maroon">◐ Theme</button><button onClick={() => { const next = Math.max(20, fontSize - 4); setFontSize(next); window.localStorage.setItem("sunesisWordFontSize", String(next)); }} className="rounded-lg border border-line bg-white px-3 py-2 text-sm font-bold text-maroon">−</button><button onClick={() => { const next = fontSize + 4; setFontSize(next); window.localStorage.setItem("sunesisWordFontSize", String(next)); }} className="rounded-lg border border-line bg-white px-3 py-2 text-sm font-bold text-maroon">+</button><button onClick={() => setContent((value) => `${value}${value ? "\n" : ""}• `)} className="rounded-lg border border-line bg-white px-3 py-2 text-sm font-bold text-maroon">• Bullet</button></div><textarea value={content} onChange={(e) => setContent(e.target.value)} spellCheck className={`min-h-[420px] w-full resize-y rounded-2xl border p-8 outline-none ${light ? "border-line bg-white text-ink" : "border-[#402528] bg-[#241013] text-white"} focus:ring-4 focus:ring-tint`} style={{ fontSize }} placeholder="Start writing here..." /><p className="mt-3 text-xs text-muted">Enter = new line · Shift + Enter = save</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={save}>▣ Save write-up</Button><button onClick={removeLast} className="rounded-xl border border-line bg-white px-4 py-3 text-sm font-bold text-maroon">Delete last</button><button onClick={clear} className="rounded-xl border border-red-200 bg-white px-4 py-3 text-sm font-bold text-red-700">Clear all</button></div>{entries.length > 0 && <section className="mt-10 rounded-2xl border border-line bg-white p-6"><h2 className="font-bold text-maroon">Saved write-ups</h2><div className="mt-4 grid gap-3">{entries.map((entry) => <button key={entry.id} onClick={() => setContent(entry.content)} className="rounded-xl bg-soft p-4 text-left text-sm text-ink hover:ring-2 hover:ring-tint">{entry.content.slice(0, 100)}{entry.content.length > 100 ? "..." : ""}</button>)}</div></section>}</div></WorkspaceGuard>;
}
